### ISSUE TITLE
Private channels are not saved

### ISSUE THREAD

**Issue by gmrukwa** [miodeqqq/django-slack-storage#1]
Tasks complete with 'Finished' state, but no private channel was fetched from Slack.

**Comment by miodeqqq** [comment]
@gmrukwa You must belong to the private channels you want to fetch. Can you verify if you've got permissions ?

**Comment by gmrukwa** [comment]
I belong to two channels, which I want to fetch. Neither appears in the list, nor the messages from there.

**Comment by miodeqqq** [comment]
@gmrukwa 
Well, now I got your point. You can't fetch private messages. All you can do (so far) is to fetch private channels's names and its description (useless for now, I know). And I'm not even sure if Slack API allows to do that. Well, we've gotta dig deeper I believe :)
